#pragma once

#include <iostream>
#include <string>
#include <memory>
#include <fstream>
#include <sstream>
#include <cstring>
#include <set>
#include <map>
#include <vector>
#include <algorithm>
#include <memory>
#include <utility>
#include <initializer_list>
#include <functional>

using std::cout;
using std::cin;
using std::endl;
using std::string;
using std::make_shared;
using std::ifstream;
using std::ofstream;
using std::istringstream;
using std::ostringstream;
using std::nothrow;
using std::shared_ptr;
using std::unique_ptr;
using std::weak_ptr;
using std::set;
using std::map;
using std::istream;
using std::ostream;
using std::vector;
using std::to_string;
using std::allocator;
using std::pair;
using std::initializer_list;
using std::uninitialized_copy;
using std::multiplies;
using std::modulus;